# Scraping IMDB con Selenium

In [133]:
%reset -f

In [134]:
import csv
import time
import pandas as pd
from selenium import webdriver
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.common.action_chains import ActionChains
import warnings
warnings.filterwarnings('ignore')

In [135]:
def extract_review_data(review_elements, i):
    review_data = []
    
    for x in review_elements:
        data = {}

        # Estrai il titolo
        titolo = x.find_elements(By.CLASS_NAME,"ipc-title__text")
        data["titolo"] = titolo[0].text

        # Estrai rating
        rt = x.find_elements(By.CLASS_NAME,"ipc-rating-star--rating")
        if rt:  # Check if the list has at least one element
            data["rating"] = rt[0].text
        else:
            data["rating"] = None

        # Estrai recensione
        recensione = x.find_elements(By.CLASS_NAME,"ipc-html-content-inner-div")
        data["recensione"]=recensione[0].text

        # estrai numero upvotes
        upvote = x.find_elements(By.CLASS_NAME,"ipc-voting__label__count--up")
        data["upvote"]=upvote[0].text

        # estrai numero downvotes
        downvote = x.find_elements(By.CLASS_NAME,"ipc-voting__label__count--down")
        data["downvote"]=downvote[0].text

        # inserire numero episodio
        data["episodio"]=i

        review_data.append(data)

    return review_data

In [143]:
def data_frame_review_data(url, x, s=20) :

# 1.PERCOSO DEL DRIVER 
    service = webdriver.ChromeService('/Users/Hp_pc/OneDrive/Desktop/Uni/LM/1_2024-2025/SocialMedia/Lab/web_scraping/chromedriver.exe')
    driver = webdriver.Chrome(service=service)
    driver.get(url)

# 2.Clicca tasto accetta 
    time.sleep(10)
    driver.find_element(By.CSS_SELECTOR, '[data-testid="accept-button"]').click()

# 3.Click bottone per visualizzare tutti le  recensioni
    button = driver.find_element(By.XPATH, "//*[@id='__next']/main/div/section/div/section/div/div[1]/section[1]/div[3]/div/span[2]/button")

# Scorrere fino al pulsante
    driver.execute_script("arguments[0].scrollIntoView();", button)

# Attendi un breve periodo per permettere alla pagina di aggiornarsi
    time.sleep(4)

# Clicca sul pulsante
    button.click()

# 4. CERCA e CLICCA TUTTI i bottoni Spoiler

    time.sleep(s)
    print("\nCerca bottoni Spoiler...")
    buttons = driver.find_elements(By.TAG_NAME, "button")
    
    spoiler_count = 0
    spoiler_buttons_found = []
    
# Prima conta quanti bottoni Spoiler esistono
    for btn in buttons:
        try:
            btn_text = btn.text.strip().lower()
            if "spoiler" in btn_text:
                spoiler_buttons_found.append(btn)
        except:
            continue
    
    print(f"Trovati {len(spoiler_buttons_found)} bottoni Spoiler")
    
# Ora cliccali tutti
    for i, btn in enumerate(spoiler_buttons_found):
        try:
            # Fai scroll fino al bottone per essere visibile
            driver.execute_script("arguments[0].scrollIntoView({behavior: 'smooth', block: 'center'});", btn)
            time.sleep(3)
            
        # Clicca il bottone
            btn.click()
            spoiler_count += 1
            print(f"  ✓ Cliccato bottone Spoiler #{spoiler_count}")
            time.sleep(1)
            
        except Exception as e:
            print(f"  ✗ Errore cliccando bottone {i+1}: {str(e)[:50]}...")
            continue
    
    print(f"\n✅ Totale Spoiler cliccati: {spoiler_count}")

# 5.Estrai dati recensioni
    review_cards = driver.find_elements(By.CLASS_NAME, "user-review-item")

    review_data = extract_review_data(review_cards, x)

    df = pd.DataFrame(review_data)
    driver.close()
    return df

Scraping recensioni Episodio 1 stagione 5

In [137]:
# url pagina imdb recensioni episodi stagione 5
url=['https://www.imdb.com/it/title/tt18268644/reviews/?ref_=tt_ov_ururv', "https://www.imdb.com/it/title/tt21914626/reviews/?ref_=tt_ururv_sm",
     "https://www.imdb.com/it/title/tt21912360/reviews/?ref_=tt_ururv_sm", "https://www.imdb.com/it/title/tt21914648/reviews/?ref_=tt_ururv_sm", 
     "https://www.imdb.com/it/title/tt21912384/reviews/?ref_=tt_ururv_sm", "https://www.imdb.com/it/title/tt21912386/reviews/?ref_=tt_ururv_sm", 
     "https://www.imdb.com/it/title/tt21912390/reviews/?ref_=tt_ururv_sm", "https://www.imdb.com/it/title/tt21914684/reviews/?ref_=tt_ururv_sm"]

In [138]:
# estrazione dati recensioni primo episodio quinta stagione
df = data_frame_review_data(url[0], 1)

df

Cerca bottoni Spoiler...
Trovati 50 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28
  ✓ Cliccato bottone Spoiler #29
  ✓ Cliccato bottone Spoiler #30
  ✓ Cliccato bottone Spoiler #31
  ✓ Cliccato bottone Spoiler #32
  ✓ Cliccato bottone Spoiler #33
  ✓ Cliccato bottone Spoiler #34
  ✓ Cliccato bottone Spoiler #35
  ✓ Cliccato bottone Spoiler #36
  ✓ Cliccato bottone Spoiler #37
  ✓ Cliccato bottone Spoiler #38
  ✓ Cliccato bottone Spoiler #39
  ✓ Cliccato bottone Spoiler #40
  ✓ Cliccato bottone Spoiler #41
  ✓ Cliccato bottone Spoiler #42
  ✓ Cliccato bottone Spoiler #43
  ✓ Cliccato bottone Spoiler #44
  ✓ Cliccato bottone Spoiler #45
  ✓ Cliccato bottone Spoiler #46
  ✓ Cliccato bottone Spoiler #47
  ✓ Cliccato bottone Spoiler #48
  ✓ Cliccato bottone Spoiler #49
  ✓ Cliccato bottone Spoiler #50

✅ Totale Spoiler cliccati: 50

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,49
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,49
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,49
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,49
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,49
...,...,...,...,...,...,...
127,Such a hard watch..,1,This episode was just absolutely HORRIBLE. The...,6,11,49
128,Something strange,5,High hopes for season 5 after the cliffhanger ...,3,4,49
129,Puberty took a decade!,5,The first episode of Season 5 feels like catch...,2,2,49
130,Not worth the wait,2,I really wanted to love this but it was honest...,2,2,49
131,So so,5,Not sure how to explain this but it was just b...,4,9,49

In [139]:
# estrazione dati recensioni secondo episodio quinta stagione
df_temp = data_frame_review_data(url[1], 2) # estrazione dati recensioni secondo episodio

df = pd.concat([df, df_temp], ignore_index=True) # uniamo i dati al dataset

df

Cerca bottoni Spoiler...
Trovati 54 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28
  ✓ Cliccato bottone Spoiler #29
  ✓ Cliccato bottone Spoiler #30
  ✓ Cliccato bottone Spoiler #31
  ✓ Cliccato bottone Spoiler #32
  ✓ Cliccato bottone Spoiler #33
  ✓ Cliccato bottone Spoiler #34
  ✓ Cliccato bottone Spoiler #35
  ✓ Cliccato bottone Spoiler #36
  ✓ Cliccato bottone Spoiler #37
  ✓ Cliccato bottone Spoiler #38
  ✓ Cliccato bottone Spoiler #39
  ✓ Cliccato bottone Spoiler #40
  ✓ Cliccato bottone Spoiler #41
  ✓ Cliccato bottone Spoiler #42
  ✓ Cliccato bottone Spoiler #43
  ✓ Cliccato bottone Spoiler #44
  ✓ Cliccato bottone Spoiler #45
  ✓ Cliccato bottone Spoiler #46
  ✓ Cliccato bottone Spoiler #47
  ✓ Cliccato bottone Spoiler #48
  ✓ Cliccato bottone Spoiler #49
  ✓ Cliccato bottone Spoiler #50
  ✓ Cliccato bottone Spoiler #51
  ✓ Cliccato bottone Spoiler #52
  ✓ Cliccato bottone Spoiler #53
  ✓ Cliccato bottone Spoiler #54

✅ Totale Spoiler cliccati: 54

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,49
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,49
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,49
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,49
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,49
...,...,...,...,...,...,...
208,COUPLES,8,This episode is a huge improvement compared to...,0,0,53
209,loyalty over urgency,7,Chapter two settles in instead of pulling me f...,0,0,53
210,Hopes crushed,1,I've seen better acting in middle school music...,18,28,53
211,Boooooring. Two episodes wasted already.,5,So it took them forever to come back with the ...,3,2,53
212,Robin and Will are the best pairing,1,I can't believe they didn't think of this soon...,2,10,53

In [140]:
# estrazione dati recensioni terzo episodio quinta stagione
df_temp = data_frame_review_data(url[2], 3) # estrazione dati recensioni settimo episodio

df = pd.concat([df, df_temp], ignore_index=True) # uniamo i dati al dataset

df

Cerca bottoni Spoiler...
Trovati 28 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28

✅ Totale Spoiler cliccati: 28

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,49
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,49
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,49
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,49
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,49
...,...,...,...,...,...,...
270,Sad state of affairs - another weak episode,5,The Duffer brothers shouldn't have given in to...,2,2,27
271,They had one job,6,Plan was cool to kidnap the family but then th...,2,1,27
272,"High Quality, Low Velocity",7,"""Stranger Things"" S5 E3 continues to prioritiz...",4,8,27
273,Can we relax,7,With the GD (god blank) wtf is going on this s...,3,7,27
274,"easy to watch, hard to feel excited",7,Chapter three keeps the same tone as before an...,0,0,27

In [141]:
# estrazione dati recensioni quarto episodio quinta stagione. s maggiore perchè numero recensioni molto più ampio
df_temp = data_frame_review_data(url[3], 4, s=120) # estrazione dati recensioni settimo episodio

df = pd.concat([df, df_temp], ignore_index=True) # uniamo i dati al dataset

df

Cerca bottoni Spoiler...
Trovati 253 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28
  ✓ Cliccato bottone Spoiler #29
  ✓ Cliccato bottone Spoiler #30
  ✓ Cliccato bottone Spoiler #31
  ✓ Cliccato bottone Spoiler #32
  ✓ Cliccato bottone Spoiler #33
  ✓ Cliccato bottone Spoiler #34
  ✓ Cliccato bottone Spoiler #35
  ✓ Cliccato bottone Spoiler #36
  ✓ Cliccato bottone Spoiler #37
  ✓ Cliccato bottone Spoiler #38
  ✓ Cliccato bottone Spoiler #39
  ✓ Cliccato bottone Spoiler #40
  ✓ Cliccato bottone Spoiler #41
  ✓ Cliccato bottone Spoiler #42
  ✓ Cliccato bottone Spoiler #43
  ✓ Cliccato bottone Spoiler #44
  ✓ Cliccato bottone Spoiler #45
  ✓ Cliccato bottone Spoiler #46
  ✓ Cliccato bottone Spoiler #47
  ✓ Cliccato bottone Spoiler #48
  ✓ Cliccato bottone Spoiler #49
  ✓ Cliccato bottone Spoiler #50
  ✓ Cliccato bottone Spoiler #51
  ✓ Cliccato bottone Spoiler #52
  ✓ Cliccato bottone Spoiler #53
  ✓ Cliccato bottone Spoiler #54
  ✓ Cliccato bottone Spoiler #55
  ✓ Cliccato bottone Spoiler #56
  ✓ Cliccato bottone Spoiler #57
  ✓ Cliccato bottone Spoiler #58
  ✓ Cliccato bottone Spoiler #59
  ✓ Cliccato bottone Spoiler #60
  ✓ Cliccato bottone Spoiler #61
  ✓ Cliccato bottone Spoiler #62
  ✓ Cliccato bottone Spoiler #63
  ✓ Cliccato bottone Spoiler #64
  ✓ Cliccato bottone Spoiler #65
  ✓ Cliccato bottone Spoiler #66
  ✓ Cliccato bottone Spoiler #67
  ✓ Cliccato bottone Spoiler #68
  ✓ Cliccato bottone Spoiler #69
  ✓ Cliccato bottone Spoiler #70
  ✓ Cliccato bottone Spoiler #71
  ✓ Cliccato bottone Spoiler #72
  ✓ Cliccato bottone Spoiler #73
  ✓ Cliccato bottone Spoiler #74
  ✓ Cliccato bottone Spoiler #75
  ✓ Cliccato bottone Spoiler #76
  ✓ Cliccato bottone Spoiler #77
  ✓ Cliccato bottone Spoiler #78
  ✓ Cliccato bottone Spoiler #79
  ✓ Cliccato bottone Spoiler #80
  ✓ Cliccato bottone Spoiler #81
  ✓ Cliccato bottone Spoiler #82
  ✓ Cliccato bottone Spoiler #83
  ✓ Cliccato bottone Spoiler #84
  ✓ Cliccato bottone Spoiler #85
  ✓ Cliccato bottone Spoiler #86
  ✓ Cliccato bottone Spoiler #87
  ✓ Cliccato bottone Spoiler #88
  ✓ Cliccato bottone Spoiler #89
  ✓ Cliccato bottone Spoiler #90
  ✓ Cliccato bottone Spoiler #91
  ✓ Cliccato bottone Spoiler #92
  ✓ Cliccato bottone Spoiler #93
  ✓ Cliccato bottone Spoiler #94
  ✓ Cliccato bottone Spoiler #95
  ✓ Cliccato bottone Spoiler #96
  ✓ Cliccato bottone Spoiler #97
  ✓ Cliccato bottone Spoiler #98
  ✓ Cliccato bottone Spoiler #99
  ✓ Cliccato bottone Spoiler #100
  ✓ Cliccato bottone Spoiler #101
  ✓ Cliccato bottone Spoiler #102
  ✓ Cliccato bottone Spoiler #103
  ✓ Cliccato bottone Spoiler #104
  ✓ Cliccato bottone Spoiler #105
  ✓ Cliccato bottone Spoiler #106
  ✓ Cliccato bottone Spoiler #107
  ✓ Cliccato bottone Spoiler #108
  ✓ Cliccato bottone Spoiler #109
  ✓ Cliccato bottone Spoiler #110
  ✓ Cliccato bottone Spoiler #111
  ✓ Cliccato bottone Spoiler #112
  ✓ Cliccato bottone Spoiler #113
  ✓ Cliccato bottone Spoiler #114
  ✓ Cliccato bottone Spoiler #115
  ✓ Cliccato bottone Spoiler #116
  ✓ Cliccato bottone Spoiler #117
  ✓ Cliccato bottone Spoiler #118
  ✓ Cliccato bottone Spoiler #119
  ✓ Cliccato bottone Spoiler #120
  ✓ Cliccato bottone Spoiler #121
  ✓ Cliccato bottone Spoiler #122
  ✓ Cliccato bottone Spoiler #123
  ✓ Cliccato bottone Spoiler #124
  ✓ Cliccato bottone Spoiler #125
  ✓ Cliccato bottone Spoiler #126
  ✓ Cliccato bottone Spoiler #127
  ✓ Cliccato bottone Spoiler #128
  ✓ Cliccato bottone Spoiler #129
  ✓ Cliccato bottone Spoiler #130
  ✓ Cliccato bottone Spoiler #131
  ✓ Cliccato bottone Spoiler #132
  ✓ Cliccato bottone Spoiler #133
  ✓ Cliccato bottone Spoiler #134
  ✓ Cliccato bottone Spoiler #135
  ✓ Cliccato bottone Spoiler #136
  ✓ Cliccato bottone Spoiler #137
  ✓ Cliccato bottone Spoiler #138
  ✓ Cliccato bottone Spoiler #139
  ✓ Cliccato bottone Spoiler #140
  ✓ Cliccato bottone Spoiler #141
  ✓ Cliccato bottone Spoiler #142
  ✓ Cliccato bottone Spoiler #143
  ✓ Cliccato bottone Spoiler #144
  ✓ Cliccato bottone Spoiler #145
  ✓ Cliccato bottone Spoiler #146
  ✓ Cliccato bottone Spoiler #147
  ✓ Cliccato bottone Spoiler #148
  ✓ Cliccato bottone Spoiler #149
  ✓ Cliccato bottone Spoiler #150
  ✓ Cliccato bottone Spoiler #151
  ✓ Cliccato bottone Spoiler #152
  ✓ Cliccato bottone Spoiler #153
  ✓ Cliccato bottone Spoiler #154
  ✓ Cliccato bottone Spoiler #155
  ✓ Cliccato bottone Spoiler #156
  ✓ Cliccato bottone Spoiler #157
  ✓ Cliccato bottone Spoiler #158
  ✓ Cliccato bottone Spoiler #159
  ✓ Cliccato bottone Spoiler #160
  ✓ Cliccato bottone Spoiler #161
  ✓ Cliccato bottone Spoiler #162
  ✓ Cliccato bottone Spoiler #163
  ✓ Cliccato bottone Spoiler #164
  ✓ Cliccato bottone Spoiler #165
  ✓ Cliccato bottone Spoiler #166
  ✓ Cliccato bottone Spoiler #167
  ✓ Cliccato bottone Spoiler #168
  ✓ Cliccato bottone Spoiler #169
  ✓ Cliccato bottone Spoiler #170
  ✓ Cliccato bottone Spoiler #171
  ✓ Cliccato bottone Spoiler #172
  ✓ Cliccato bottone Spoiler #173
  ✓ Cliccato bottone Spoiler #174
  ✓ Cliccato bottone Spoiler #175
  ✓ Cliccato bottone Spoiler #176
  ✓ Cliccato bottone Spoiler #177
  ✓ Cliccato bottone Spoiler #178
  ✓ Cliccato bottone Spoiler #179
  ✓ Cliccato bottone Spoiler #180
  ✓ Cliccato bottone Spoiler #181
  ✓ Cliccato bottone Spoiler #182
  ✓ Cliccato bottone Spoiler #183
  ✓ Cliccato bottone Spoiler #184
  ✓ Cliccato bottone Spoiler #185
  ✓ Cliccato bottone Spoiler #186
  ✓ Cliccato bottone Spoiler #187
  ✓ Cliccato bottone Spoiler #188
  ✓ Cliccato bottone Spoiler #189
  ✓ Cliccato bottone Spoiler #190
  ✓ Cliccato bottone Spoiler #191
  ✓ Cliccato bottone Spoiler #192
  ✓ Cliccato bottone Spoiler #193
  ✓ Cliccato bottone Spoiler #194
  ✓ Cliccato bottone Spoiler #195
  ✓ Cliccato bottone Spoiler #196
  ✓ Cliccato bottone Spoiler #197
  ✓ Cliccato bottone Spoiler #198
  ✓ Cliccato bottone Spoiler #199
  ✓ Cliccato bottone Spoiler #200
  ✓ Cliccato bottone Spoiler #201
  ✓ Cliccato bottone Spoiler #202
  ✓ Cliccato bottone Spoiler #203
  ✓ Cliccato bottone Spoiler #204
  ✓ Cliccato bottone Spoiler #205
  ✓ Cliccato bottone Spoiler #206
  ✓ Cliccato bottone Spoiler #207
  ✓ Cliccato bottone Spoiler #208
  ✓ Cliccato bottone Spoiler #209
  ✓ Cliccato bottone Spoiler #210
  ✓ Cliccato bottone Spoiler #211
  ✓ Cliccato bottone Spoiler #212
  ✓ Cliccato bottone Spoiler #213
  ✓ Cliccato bottone Spoiler #214
  ✓ Cliccato bottone Spoiler #215
  ✓ Cliccato bottone Spoiler #216
  ✓ Cliccato bottone Spoiler #217
  ✓ Cliccato bottone Spoiler #218
  ✓ Cliccato bottone Spoiler #219
  ✓ Cliccato bottone Spoiler #220
  ✓ Cliccato bottone Spoiler #221
  ✓ Cliccato bottone Spoiler #222
  ✓ Cliccato bottone Spoiler #223
  ✓ Cliccato bottone Spoiler #224
  ✓ Cliccato bottone Spoiler #225
  ✓ Cliccato bottone Spoiler #226
  ✓ Cliccato bottone Spoiler #227
  ✓ Cliccato bottone Spoiler #228
  ✓ Cliccato bottone Spoiler #229
  ✓ Cliccato bottone Spoiler #230
  ✓ Cliccato bottone Spoiler #231
  ✓ Cliccato bottone Spoiler #232
  ✓ Cliccato bottone Spoiler #233
  ✓ Cliccato bottone Spoiler #234
  ✓ Cliccato bottone Spoiler #235
  ✓ Cliccato bottone Spoiler #236
  ✓ Cliccato bottone Spoiler #237
  ✓ Cliccato bottone Spoiler #238
  ✓ Cliccato bottone Spoiler #239
  ✓ Cliccato bottone Spoiler #240
  ✓ Cliccato bottone Spoiler #241
  ✓ Cliccato bottone Spoiler #242
  ✓ Cliccato bottone Spoiler #243
  ✓ Cliccato bottone Spoiler #244
  ✓ Cliccato bottone Spoiler #245
  ✓ Cliccato bottone Spoiler #246
  ✓ Cliccato bottone Spoiler #247
  ✓ Cliccato bottone Spoiler #248
  ✓ Cliccato bottone Spoiler #249
  ✓ Cliccato bottone Spoiler #250
  ✓ Cliccato bottone Spoiler #251
  ✓ Cliccato bottone Spoiler #252
  ✓ Cliccato bottone Spoiler #253

✅ Totale Spoiler cliccati: 253

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,49
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,49
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,49
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,49
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,49
...,...,...,...,...,...,...
749,Superb peak ending,10,Peak ending to Volume 1 with out doubt outstan...,0,4,252
750,Absolutely Astonishing,10,Biblical in scope.\n\nThe chess pieces are mov...,0,0,252
751,Will the Warg,None,"Alright, Duffers - ya got me this time. Part 1...",0,5,252
752,Best Episode Of The Show,None,"Firstly, let me say that this was a peak cliff...",0,0,252
753,amazing episode!,None,"So much happened in this episode, and it was p...",0,2,252

In [142]:
# estrazione dati recensioni quinto episodio quinta stagione
df_temp = data_frame_review_data(url[4], 5) # estrazione dati recensioni settimo episodio

df = pd.concat([df, df_temp], ignore_index=True) # uniamo i dati al dataset

df

Cerca bottoni Spoiler...
Trovati 73 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28
  ✓ Cliccato bottone Spoiler #29
  ✓ Cliccato bottone Spoiler #30
  ✓ Cliccato bottone Spoiler #31
  ✓ Cliccato bottone Spoiler #32
  ✓ Cliccato bottone Spoiler #33
  ✓ Cliccato bottone Spoiler #34
  ✓ Cliccato bottone Spoiler #35
  ✓ Cliccato bottone Spoiler #36
  ✓ Cliccato bottone Spoiler #37
  ✓ Cliccato bottone Spoiler #38
  ✓ Cliccato bottone Spoiler #39
  ✓ Cliccato bottone Spoiler #40
  ✓ Cliccato bottone Spoiler #41
  ✓ Cliccato bottone Spoiler #42
  ✓ Cliccato bottone Spoiler #43
  ✓ Cliccato bottone Spoiler #44
  ✓ Cliccato bottone Spoiler #45
  ✓ Cliccato bottone Spoiler #46
  ✓ Cliccato bottone Spoiler #47
  ✓ Cliccato bottone Spoiler #48
  ✓ Cliccato bottone Spoiler #49
  ✓ Cliccato bottone Spoiler #50
  ✓ Cliccato bottone Spoiler #51
  ✓ Cliccato bottone Spoiler #52
  ✓ Cliccato bottone Spoiler #53
  ✓ Cliccato bottone Spoiler #54
  ✓ Cliccato bottone Spoiler #55
  ✓ Cliccato bottone Spoiler #56
  ✓ Cliccato bottone Spoiler #57
  ✓ Cliccato bottone Spoiler #58
  ✓ Cliccato bottone Spoiler #59
  ✓ Cliccato bottone Spoiler #60
  ✓ Cliccato bottone Spoiler #61
  ✓ Cliccato bottone Spoiler #62
  ✓ Cliccato bottone Spoiler #63
  ✓ Cliccato bottone Spoiler #64
  ✓ Cliccato bottone Spoiler #65
  ✓ Cliccato bottone Spoiler #66
  ✓ Cliccato bottone Spoiler #67
  ✓ Cliccato bottone Spoiler #68
  ✓ Cliccato bottone Spoiler #69
  ✓ Cliccato bottone Spoiler #70
  ✓ Cliccato bottone Spoiler #71
  ✓ Cliccato bottone Spoiler #72
  ✓ Cliccato bottone Spoiler #73

✅ Totale Spoiler cliccati: 73

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,49
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,49
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,49
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,49
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,49
...,...,...,...,...,...,...
927,Absolutely terrible,3,"This was shockingly bad. Forced drama, bad act...",0,0,72
928,CUT SCENES,1,What it was???\n\nI am very disappointed. Netf...,0,3,72
929,DELETED SCENES!!!!,1,I am beyond frustrated with the way Netflix ha...,0,2,72
930,Hell nah,None,I'm rating this a 1 because it felt so rushed ...,0,4,72
931,Stop cutting episodes,None,For the petition to release the unseen footage...,0,3,72

In [144]:

df["episodio"] = df["episodio"].map(
    {49: 1, 53: 2, 27: 3, 252: 4, 72:5}
)

df

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,1
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,1
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,1
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,1
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,1
...,...,...,...,...,...,...
927,Absolutely terrible,3,"This was shockingly bad. Forced drama, bad act...",0,0,5
928,CUT SCENES,1,What it was???\n\nI am very disappointed. Netf...,0,3,5
929,DELETED SCENES!!!!,1,I am beyond frustrated with the way Netflix ha...,0,2,5
930,Hell nah,None,I'm rating this a 1 because it felt so rushed ...,0,4,5
931,Stop cutting episodes,None,For the petition to release the unseen footage...,0,3,5

In [152]:
# estrazione dati recensioni sesto episodio quinta stagione
df_temp = data_frame_review_data(url[5], 6) # estrazione dati recensioni sesto episodio

df = pd.concat([df, df_temp], ignore_index=True) # uniamo i dati al dataset

df

Cerca bottoni Spoiler...
Trovati 161 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28
  ✓ Cliccato bottone Spoiler #29
  ✓ Cliccato bottone Spoiler #30
  ✓ Cliccato bottone Spoiler #31
  ✓ Cliccato bottone Spoiler #32
  ✓ Cliccato bottone Spoiler #33
  ✓ Cliccato bottone Spoiler #34
  ✓ Cliccato bottone Spoiler #35
  ✓ Cliccato bottone Spoiler #36
  ✓ Cliccato bottone Spoiler #37
  ✓ Cliccato bottone Spoiler #38
  ✓ Cliccato bottone Spoiler #39
  ✓ Cliccato bottone Spoiler #40
  ✓ Cliccato bottone Spoiler #41
  ✓ Cliccato bottone Spoiler #42
  ✓ Cliccato bottone Spoiler #43
  ✓ Cliccato bottone Spoiler #44
  ✓ Cliccato bottone Spoiler #45
  ✓ Cliccato bottone Spoiler #46
  ✓ Cliccato bottone Spoiler #47
  ✓ Cliccato bottone Spoiler #48
  ✓ Cliccato bottone Spoiler #49
  ✓ Cliccato bottone Spoiler #50
  ✓ Cliccato bottone Spoiler #51
  ✓ Cliccato bottone Spoiler #52
  ✓ Cliccato bottone Spoiler #53
  ✓ Cliccato bottone Spoiler #54
  ✓ Cliccato bottone Spoiler #55
  ✓ Cliccato bottone Spoiler #56
  ✓ Cliccato bottone Spoiler #57
  ✓ Cliccato bottone Spoiler #58
  ✓ Cliccato bottone Spoiler #59
  ✓ Cliccato bottone Spoiler #60
  ✓ Cliccato bottone Spoiler #61
  ✓ Cliccato bottone Spoiler #62
  ✓ Cliccato bottone Spoiler #63
  ✓ Cliccato bottone Spoiler #64
  ✓ Cliccato bottone Spoiler #65
  ✓ Cliccato bottone Spoiler #66
  ✓ Cliccato bottone Spoiler #67
  ✓ Cliccato bottone Spoiler #68
  ✓ Cliccato bottone Spoiler #69
  ✓ Cliccato bottone Spoiler #70
  ✓ Cliccato bottone Spoiler #71
  ✓ Cliccato bottone Spoiler #72
  ✓ Cliccato bottone Spoiler #73
  ✓ Cliccato bottone Spoiler #74
  ✓ Cliccato bottone Spoiler #75
  ✓ Cliccato bottone Spoiler #76
  ✓ Cliccato bottone Spoiler #77
  ✓ Cliccato bottone Spoiler #78
  ✓ Cliccato bottone Spoiler #79
  ✓ Cliccato bottone Spoiler #80
  ✓ Cliccato bottone Spoiler #81
  ✓ Cliccato bottone Spoiler #82
  ✓ Cliccato bottone Spoiler #83
  ✓ Cliccato bottone Spoiler #84
  ✓ Cliccato bottone Spoiler #85
  ✓ Cliccato bottone Spoiler #86
  ✓ Cliccato bottone Spoiler #87
  ✓ Cliccato bottone Spoiler #88
  ✓ Cliccato bottone Spoiler #89
  ✓ Cliccato bottone Spoiler #90
  ✓ Cliccato bottone Spoiler #91
  ✓ Cliccato bottone Spoiler #92
  ✓ Cliccato bottone Spoiler #93
  ✓ Cliccato bottone Spoiler #94
  ✓ Cliccato bottone Spoiler #95
  ✓ Cliccato bottone Spoiler #96
  ✓ Cliccato bottone Spoiler #97
  ✓ Cliccato bottone Spoiler #98
  ✓ Cliccato bottone Spoiler #99
  ✓ Cliccato bottone Spoiler #100
  ✓ Cliccato bottone Spoiler #101
  ✓ Cliccato bottone Spoiler #102
  ✓ Cliccato bottone Spoiler #103
  ✓ Cliccato bottone Spoiler #104
  ✓ Cliccato bottone Spoiler #105
  ✓ Cliccato bottone Spoiler #106
  ✓ Cliccato bottone Spoiler #107
  ✓ Cliccato bottone Spoiler #108
  ✓ Cliccato bottone Spoiler #109
  ✓ Cliccato bottone Spoiler #110
  ✓ Cliccato bottone Spoiler #111
  ✓ Cliccato bottone Spoiler #112
  ✓ Cliccato bottone Spoiler #113
  ✓ Cliccato bottone Spoiler #114
  ✓ Cliccato bottone Spoiler #115
  ✓ Cliccato bottone Spoiler #116
  ✓ Cliccato bottone Spoiler #117
  ✓ Cliccato bottone Spoiler #118
  ✓ Cliccato bottone Spoiler #119
  ✓ Cliccato bottone Spoiler #120
  ✓ Cliccato bottone Spoiler #121
  ✓ Cliccato bottone Spoiler #122
  ✓ Cliccato bottone Spoiler #123
  ✓ Cliccato bottone Spoiler #124
  ✓ Cliccato bottone Spoiler #125
  ✓ Cliccato bottone Spoiler #126
  ✓ Cliccato bottone Spoiler #127
  ✓ Cliccato bottone Spoiler #128
  ✓ Cliccato bottone Spoiler #129
  ✓ Cliccato bottone Spoiler #130
  ✓ Cliccato bottone Spoiler #131
  ✓ Cliccato bottone Spoiler #132
  ✓ Cliccato bottone Spoiler #133
  ✓ Cliccato bottone Spoiler #134
  ✓ Cliccato bottone Spoiler #135
  ✓ Cliccato bottone Spoiler #136
  ✓ Cliccato bottone Spoiler #137
  ✓ Cliccato bottone Spoiler #138
  ✓ Cliccato bottone Spoiler #139
  ✓ Cliccato bottone Spoiler #140
  ✓ Cliccato bottone Spoiler #141
  ✓ Cliccato bottone Spoiler #142
  ✓ Cliccato bottone Spoiler #143
  ✓ Cliccato bottone Spoiler #144
  ✓ Cliccato bottone Spoiler #145
  ✓ Cliccato bottone Spoiler #146
  ✓ Cliccato bottone Spoiler #147
  ✓ Cliccato bottone Spoiler #148
  ✓ Cliccato bottone Spoiler #149
  ✓ Cliccato bottone Spoiler #150
  ✓ Cliccato bottone Spoiler #151
  ✓ Cliccato bottone Spoiler #152
  ✓ Cliccato bottone Spoiler #153
  ✓ Cliccato bottone Spoiler #154
  ✓ Cliccato bottone Spoiler #155
  ✓ Cliccato bottone Spoiler #156
  ✓ Cliccato bottone Spoiler #157
  ✓ Cliccato bottone Spoiler #158
  ✓ Cliccato bottone Spoiler #159
  ✓ Cliccato bottone Spoiler #160
  ✓ Cliccato bottone Spoiler #161

✅ Totale Spoiler cliccati: 161

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,1
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,1
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,1
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,1
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,1
...,...,...,...,...,...,...
1195,"Good acting, but felt like nothing hsppened",5,"After all the buildup in Episode 5, I expected...",0,2,6
1196,People are weird,None,Episode 6 of Stranger Things Season 5 is absol...,0,2,6
1197,Invisible Barrier in Stranger Things S05E06 - ...,None,Stranger Things S05E06 is honestly one of the ...,0,1,6
1198,The great cut of Camazotz,None,Release the full volume 2. We deserve better. ...,0,4,6
1199,DELETED SCENES,None,I'm rating this a 1 because it felt so rushed ...,0,6,6

In [159]:
# estrazione dati recensioni settimo episodio quinta stagione. s maggiore perchè numero recensioni molto più ampio
df_temp = data_frame_review_data(url[6], 7, s=420) # estrazione dati recensioni settimo episodio

df = pd.concat([df, df_temp], ignore_index=True) # uniamo i dati al dataset

df

Cerca bottoni Spoiler...
Trovati 1694 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28
  ✓ Cliccato bottone Spoiler #29
  ✓ Cliccato bottone Spoiler #30
  ✓ Cliccato bottone Spoiler #31
  ✓ Cliccato bottone Spoiler #32
  ✓ Cliccato bottone Spoiler #33
  ✓ Cliccato bottone Spoiler #34
  ✓ Cliccato bottone Spoiler #35
  ✓ Cliccato bottone Spoiler #36
  ✓ Cliccato bottone Spoiler #37
  ✓ Cliccato bottone Spoiler #38
  ✓ Cliccato bottone Spoiler #39
  ✓ Cliccato bottone Spoiler #40
  ✓ Cliccato bottone Spoiler #41
  ✓ Cliccato bottone Spoiler #42
  ✓ Cliccato bottone Spoiler #43
  ✓ Cliccato bottone Spoiler #44
  ✓ Cliccato bottone Spoiler #45
  ✓ Cliccato bottone Spoiler #46
  ✓ Cliccato bottone Spoiler #47
  ✓ Cliccato bottone Spoiler #48
  ✓ Cliccato bottone Spoiler #49
  ✓ Cliccato bottone Spoiler #50
  ✓ Cliccato bottone Spoiler #51
  ✓ Cliccato bottone Spoiler #52
  ✓ Cliccato bottone Spoiler #53
  ✓ Cliccato bottone Spoiler #54
  ✓ Cliccato bottone Spoiler #55
  ✓ Cliccato bottone Spoiler #56
  ✓ Cliccato bottone Spoiler #57
  ✓ Cliccato bottone Spoiler #58
  ✓ Cliccato bottone Spoiler #59
  ✓ Cliccato bottone Spoiler #60
  ✓ Cliccato bottone Spoiler #61
  ✓ Cliccato bottone Spoiler #62
  ✓ Cliccato bottone Spoiler #63
  ✓ Cliccato bottone Spoiler #64
  ✓ Cliccato bottone Spoiler #65
  ✓ Cliccato bottone Spoiler #66
  ✓ Cliccato bottone Spoiler #67
  ✓ Cliccato bottone Spoiler #68
  ✓ Cliccato bottone Spoiler #69
  ✓ Cliccato bottone Spoiler #70
  ✓ Cliccato bottone Spoiler #71
  ✓ Cliccato bottone Spoiler #72
  ✓ Cliccato bottone Spoiler #73
  ✓ Cliccato bottone Spoiler #74
  ✓ Cliccato bottone Spoiler #75
  ✓ Cliccato bottone Spoiler #76
  ✓ Cliccato bottone Spoiler #77
  ✓ Cliccato bottone Spoiler #78
  ✓ Cliccato bottone Spoiler #79
  ✓ Cliccato bottone Spoiler #80
  ✓ Cliccato bottone Spoiler #81
  ✓ Cliccato bottone Spoiler #82
  ✓ Cliccato bottone Spoiler #83
  ✓ Cliccato bottone Spoiler #84
  ✓ Cliccato bottone Spoiler #85
  ✓ Cliccato bottone Spoiler #86
  ✓ Cliccato bottone Spoiler #87
  ✓ Cliccato bottone Spoiler #88
  ✓ Cliccato bottone Spoiler #89
  ✓ Cliccato bottone Spoiler #90
  ✓ Cliccato bottone Spoiler #91
  ✓ Cliccato bottone Spoiler #92
  ✓ Cliccato bottone Spoiler #93
  ✓ Cliccato bottone Spoiler #94
  ✓ Cliccato bottone Spoiler #95
  ✓ Cliccato bottone Spoiler #96
  ✓ Cliccato bottone Spoiler #97
  ✓ Cliccato bottone Spoiler #98
  ✓ Cliccato bottone Spoiler #99
  ✓ Cliccato bottone Spoiler #100
  ✓ Cliccato bottone Spoiler #101
  ✓ Cliccato bottone Spoiler #102
  ✓ Cliccato bottone Spoiler #103
  ✓ Cliccato bottone Spoiler #104
  ✓ Cliccato bottone Spoiler #105
  ✓ Cliccato bottone Spoiler #106
  ✓ Cliccato bottone Spoiler #107
  ✓ Cliccato bottone Spoiler #108
  ✓ Cliccato bottone Spoiler #109
  ✓ Cliccato bottone Spoiler #110
  ✓ Cliccato bottone Spoiler #111
  ✓ Cliccato bottone Spoiler #112
  ✓ Cliccato bottone Spoiler #113
  ✓ Cliccato bottone Spoiler #114
  ✓ Cliccato bottone Spoiler #115
  ✓ Cliccato bottone Spoiler #116
  ✓ Cliccato bottone Spoiler #117
  ✓ Cliccato bottone Spoiler #118
  ✓ Cliccato bottone Spoiler #119
  ✓ Cliccato bottone Spoiler #120
  ✓ Cliccato bottone Spoiler #121
  ✓ Cliccato bottone Spoiler #122
  ✓ Cliccato bottone Spoiler #123
  ✓ Cliccato bottone Spoiler #124
  ✓ Cliccato bottone Spoiler #125
  ✓ Cliccato bottone Spoiler #126
  ✓ Cliccato bottone Spoiler #127
  ✓ Cliccato bottone Spoiler #128
  ✓ Cliccato bottone Spoiler #129
  ✓ Cliccato bottone Spoiler #130
  ✓ Cliccato bottone Spoiler #131
  ✓ Cliccato bottone Spoiler #132
  ✓ Cliccato bottone Spoiler #133
  ✓ Cliccato bottone Spoiler #134
  ✓ Cliccato bottone Spoiler #135
  ✓ Cliccato bottone Spoiler #136
  ✓ Cliccato bottone Spoiler #137
  ✓ Cliccato bottone Spoiler #138
  ✓ Cliccato bottone Spoiler #139
  ✓ Cliccato bottone Spoiler #140
  ✓ Cliccato bottone Spoiler #141
  ✓ Cliccato bottone Spoiler #142
  ✓ Cliccato bottone Spoiler #143
  ✓ Cliccato bottone Spoiler #144
  ✓ Cliccato bottone Spoiler #145
  ✓ Cliccato bottone Spoiler #146
  ✓ Cliccato bottone Spoiler #147
  ✓ Cliccato bottone Spoiler #148
  ✓ Cliccato bottone Spoiler #149
  ✓ Cliccato bottone Spoiler #150
  ✓ Cliccato bottone Spoiler #151
  ✓ Cliccato bottone Spoiler #152
  ✓ Cliccato bottone Spoiler #153
  ✓ Cliccato bottone Spoiler #154
  ✓ Cliccato bottone Spoiler #155
  ✓ Cliccato bottone Spoiler #156
  ✓ Cliccato bottone Spoiler #157
  ✓ Cliccato bottone Spoiler #158
  ✓ Cliccato bottone Spoiler #159
  ✓ Cliccato bottone Spoiler #160
  ✓ Cliccato bottone Spoiler #161
  ✓ Cliccato bottone Spoiler #162
  ✓ Cliccato bottone Spoiler #163
  ✓ Cliccato bottone Spoiler #164
  ✓ Cliccato bottone Spoiler #165
  ✓ Cliccato bottone Spoiler #166
  ✓ Cliccato bottone Spoiler #167
  ✓ Cliccato bottone Spoiler #168
  ✓ Cliccato bottone Spoiler #169
  ✓ Cliccato bottone Spoiler #170
  ✓ Cliccato bottone Spoiler #171
  ✓ Cliccato bottone Spoiler #172
  ✓ Cliccato bottone Spoiler #173
  ✓ Cliccato bottone Spoiler #174
  ✓ Cliccato bottone Spoiler #175
  ✓ Cliccato bottone Spoiler #176
  ✓ Cliccato bottone Spoiler #177
  ✓ Cliccato bottone Spoiler #178
  ✓ Cliccato bottone Spoiler #179
  ✓ Cliccato bottone Spoiler #180
  ✓ Cliccato bottone Spoiler #181
  ✓ Cliccato bottone Spoiler #182
  ✓ Cliccato bottone Spoiler #183
  ✓ Cliccato bottone Spoiler #184
  ✓ Cliccato bottone Spoiler #185
  ✓ Cliccato bottone Spoiler #186
  ✓ Cliccato bottone Spoiler #187
  ✓ Cliccato bottone Spoiler #188
  ✓ Cliccato bottone Spoiler #189
  ✓ Cliccato bottone Spoiler #190
  ✓ Cliccato bottone Spoiler #191
  ✓ Cliccato bottone Spoiler #192
  ✓ Cliccato bottone Spoiler #193
  ✓ Cliccato bottone Spoiler #194
  ✓ Cliccato bottone Spoiler #195
  ✓ Cliccato bottone Spoiler #196
  ✓ Cliccato bottone Spoiler #197
  ✓ Cliccato bottone Spoiler #198
  ✓ Cliccato bottone Spoiler #199
  ✓ Cliccato bottone Spoiler #200
  ✓ Cliccato bottone Spoiler #201
  ✓ Cliccato bottone Spoiler #202
  ✓ Cliccato bottone Spoiler #203
  ✓ Cliccato bottone Spoiler #204
  ✓ Cliccato bottone Spoiler #205
  ✓ Cliccato bottone Spoiler #206
  ✓ Cliccato bottone Spoiler #207
  ✓ Cliccato bottone Spoiler #208
  ✓ Cliccato bottone Spoiler #209
  ✓ Cliccato bottone Spoiler #210
  ✓ Cliccato bottone Spoiler #211
  ✓ Cliccato bottone Spoiler #212
  ✓ Cliccato bottone Spoiler #213
  ✓ Cliccato bottone Spoiler #214
  ✓ Cliccato bottone Spoiler #215
  ✓ Cliccato bottone Spoiler #216
  ✓ Cliccato bottone Spoiler #217
  ✓ Cliccato bottone Spoiler #218
  ✓ Cliccato bottone Spoiler #219
  ✓ Cliccato bottone Spoiler #220
  ✓ Cliccato bottone Spoiler #221
  ✓ Cliccato bottone Spoiler #222
  ✓ Cliccato bottone Spoiler #223
  ✓ Cliccato bottone Spoiler #224
  ✓ Cliccato bottone Spoiler #225
  ✓ Cliccato bottone Spoiler #226
  ✓ Cliccato bottone Spoiler #227
  ✓ Cliccato bottone Spoiler #228
  ✓ Cliccato bottone Spoiler #229
  ✓ Cliccato bottone Spoiler #230
  ✓ Cliccato bottone Spoiler #231
  ✓ Cliccato bottone Spoiler #232
  ✓ Cliccato bottone Spoiler #233
  ✓ Cliccato bottone Spoiler #234
  ✓ Cliccato bottone Spoiler #235
  ✓ Cliccato bottone Spoiler #236
  ✓ Cliccato bottone Spoiler #237
  ✓ Cliccato bottone Spoiler #238
  ✓ Cliccato bottone Spoiler #239
  ✓ Cliccato bottone Spoiler #240
  ✓ Cliccato bottone Spoiler #241
  ✓ Cliccato bottone Spoiler #242
  ✓ Cliccato bottone Spoiler #243
  ✓ Cliccato bottone Spoiler #244
  ✓ Cliccato bottone Spoiler #245
  ✓ Cliccato bottone Spoiler #246
  ✓ Cliccato bottone Spoiler #247
  ✓ Cliccato bottone Spoiler #248
  ✓ Cliccato bottone Spoiler #249
  ✓ Cliccato bottone Spoiler #250
  ✓ Cliccato bottone Spoiler #251
  ✓ Cliccato bottone Spoiler #252
  ✓ Cliccato bottone Spoiler #253
  ✓ Cliccato bottone Spoiler #254
  ✓ Cliccato bottone Spoiler #255
  ✓ Cliccato bottone Spoiler #256
  ✓ Cliccato bottone Spoiler #257
  ✓ Cliccato bottone Spoiler #258
  ✓ Cliccato bottone Spoiler #259
  ✓ Cliccato bottone Spoiler #260
  ✓ Cliccato bottone Spoiler #261
  ✓ Cliccato bottone Spoiler #262
  ✓ Cliccato bottone Spoiler #263
  ✓ Cliccato bottone Spoiler #264
  ✓ Cliccato bottone Spoiler #265
  ✓ Cliccato bottone Spoiler #266
  ✓ Cliccato bottone Spoiler #267
  ✓ Cliccato bottone Spoiler #268
  ✓ Cliccato bottone Spoiler #269
  ✓ Cliccato bottone Spoiler #270
  ✓ Cliccato bottone Spoiler #271
  ✓ Cliccato bottone Spoiler #272
  ✓ Cliccato bottone Spoiler #273
  ✓ Cliccato bottone Spoiler #274
  ✓ Cliccato bottone Spoiler #275
  ✓ Cliccato bottone Spoiler #276
  ✓ Cliccato bottone Spoiler #277
  ✓ Cliccato bottone Spoiler #278
  ✓ Cliccato bottone Spoiler #279
  ✓ Cliccato bottone Spoiler #280
  ✓ Cliccato bottone Spoiler #281
  ✓ Cliccato bottone Spoiler #282
  ✓ Cliccato bottone Spoiler #283
  ✓ Cliccato bottone Spoiler #284
  ✓ Cliccato bottone Spoiler #285
  ✓ Cliccato bottone Spoiler #286
  ✓ Cliccato bottone Spoiler #287
  ✓ Cliccato bottone Spoiler #288
  ✓ Cliccato bottone Spoiler #289
  ✓ Cliccato bottone Spoiler #290
  ✓ Cliccato bottone Spoiler #291
  ✓ Cliccato bottone Spoiler #292
  ✓ Cliccato bottone Spoiler #293
  ✓ Cliccato bottone Spoiler #294
  ✓ Cliccato bottone Spoiler #295
  ✓ Cliccato bottone Spoiler #296
  ✓ Cliccato bottone Spoiler #297
  ✓ Cliccato bottone Spoiler #298
  ✓ Cliccato bottone Spoiler #299
  ✓ Cliccato bottone Spoiler #300
  ✓ Cliccato bottone Spoiler #301
  ✓ Cliccato bottone Spoiler #302
  ✓ Cliccato bottone Spoiler #303
  ✓ Cliccato bottone Spoiler #304
  ✓ Cliccato bottone Spoiler #305
  ✓ Cliccato bottone Spoiler #306
  ✓ Cliccato bottone Spoiler #307
  ✓ Cliccato bottone Spoiler #308
  ✓ Cliccato bottone Spoiler #309
  ✓ Cliccato bottone Spoiler #310
  ✓ Cliccato bottone Spoiler #311
  ✓ Cliccato bottone Spoiler #312
  ✓ Cliccato bottone Spoiler #313
  ✓ Cliccato bottone Spoiler #314
  ✓ Cliccato bottone Spoiler #315
  ✓ Cliccato bottone Spoiler #316
  ✓ Cliccato bottone Spoiler #317
  ✓ Cliccato bottone Spoiler #318
  ✓ Cliccato bottone Spoiler #319
  ✓ Cliccato bottone Spoiler #320
  ✓ Cliccato bottone Spoiler #321
  ✓ Cliccato bottone Spoiler #322
  ✓ Cliccato bottone Spoiler #323
  ✓ Cliccato bottone Spoiler #324
  ✓ Cliccato bottone Spoiler #325
  ✓ Cliccato bottone Spoiler #326
  ✓ Cliccato bottone Spoiler #327
  ✓ Cliccato bottone Spoiler #328
  ✓ Cliccato bottone Spoiler #329
  ✓ Cliccato bottone Spoiler #330
  ✓ Cliccato bottone Spoiler #331
  ✓ Cliccato bottone Spoiler #332
  ✓ Cliccato bottone Spoiler #333
  ✓ Cliccato bottone Spoiler #334
  ✓ Cliccato bottone Spoiler #335
  ✓ Cliccato bottone Spoiler #336
  ✓ Cliccato bottone Spoiler #337
  ✓ Cliccato bottone Spoiler #338
  ✓ Cliccato bottone Spoiler #339
  ✓ Cliccato bottone Spoiler #340
  ✓ Cliccato bottone Spoiler #341
  ✓ Cliccato bottone Spoiler #342
  ✓ Cliccato bottone Spoiler #343
  ✓ Cliccato bottone Spoiler #344
  ✓ Cliccato bottone Spoiler #345
  ✓ Cliccato bottone Spoiler #346
  ✓ Cliccato bottone Spoiler #347
  ✓ Cliccato bottone Spoiler #348
  ✓ Cliccato bottone Spoiler #349
  ✓ Cliccato bottone Spoiler #350
  ✓ Cliccato bottone Spoiler #351
  ✓ Cliccato bottone Spoiler #352
  ✓ Cliccato bottone Spoiler #353
  ✓ Cliccato bottone Spoiler #354
  ✓ Cliccato bottone Spoiler #355
  ✓ Cliccato bottone Spoiler #356
  ✓ Cliccato bottone Spoiler #357
  ✓ Cliccato bottone Spoiler #358
  ✓ Cliccato bottone Spoiler #359
  ✓ Cliccato bottone Spoiler #360
  ✓ Cliccato bottone Spoiler #361
  ✓ Cliccato bottone Spoiler #362
  ✓ Cliccato bottone Spoiler #363
  ✓ Cliccato bottone Spoiler #364
  ✓ Cliccato bottone Spoiler #365
  ✓ Cliccato bottone Spoiler #366
  ✓ Cliccato bottone Spoiler #367
  ✓ Cliccato bottone Spoiler #368
  ✓ Cliccato bottone Spoiler #369
  ✓ Cliccato bottone Spoiler #370
  ✓ Cliccato bottone Spoiler #371
  ✓ Cliccato bottone Spoiler #372
  ✓ Cliccato bottone Spoiler #373
  ✓ Cliccato bottone Spoiler #374
  ✓ Cliccato bottone Spoiler #375
  ✓ Cliccato bottone Spoiler #376
  ✓ Cliccato bottone Spoiler #377
  ✓ Cliccato bottone Spoiler #378
  ✓ Cliccato bottone Spoiler #379
  ✓ Cliccato bottone Spoiler #380
  ✓ Cliccato bottone Spoiler #381
  ✓ Cliccato bottone Spoiler #382
  ✓ Cliccato bottone Spoiler #383
  ✓ Cliccato bottone Spoiler #384
  ✓ Cliccato bottone Spoiler #385
  ✓ Cliccato bottone Spoiler #386
  ✓ Cliccato bottone Spoiler #387
  ✓ Cliccato bottone Spoiler #388
  ✓ Cliccato bottone Spoiler #389
  ✓ Cliccato bottone Spoiler #390
  ✓ Cliccato bottone Spoiler #391
  ✓ Cliccato bottone Spoiler #392
  ✓ Cliccato bottone Spoiler #393
  ✓ Cliccato bottone Spoiler #394
  ✓ Cliccato bottone Spoiler #395
  ✓ Cliccato bottone Spoiler #396
  ✓ Cliccato bottone Spoiler #397
  ✓ Cliccato bottone Spoiler #398
  ✓ Cliccato bottone Spoiler #399
  ✓ Cliccato bottone Spoiler #400
  ✓ Cliccato bottone Spoiler #401
  ✓ Cliccato bottone Spoiler #402
  ✓ Cliccato bottone Spoiler #403
  ✓ Cliccato bottone Spoiler #404
  ✓ Cliccato bottone Spoiler #405
  ✓ Cliccato bottone Spoiler #406
  ✓ Cliccato bottone Spoiler #407
  ✓ Cliccato bottone Spoiler #408
  ✓ Cliccato bottone Spoiler #409
  ✓ Cliccato bottone Spoiler #410
  ✓ Cliccato bottone Spoiler #411
  ✓ Cliccato bottone Spoiler #412
  ✓ Cliccato bottone Spoiler #413
  ✓ Cliccato bottone Spoiler #414
  ✓ Cliccato bottone Spoiler #415
  ✓ Cliccato bottone Spoiler #416
  ✓ Cliccato bottone Spoiler #417
  ✓ Cliccato bottone Spoiler #418
  ✓ Cliccato bottone Spoiler #419
  ✓ Cliccato bottone Spoiler #420
  ✓ Cliccato bottone Spoiler #421
  ✓ Cliccato bottone Spoiler #422
  ✓ Cliccato bottone Spoiler #423
  ✓ Cliccato bottone Spoiler #424
  ✓ Cliccato bottone Spoiler #425
  ✓ Cliccato bottone Spoiler #426
  ✓ Cliccato bottone Spoiler #427
  ✓ Cliccato bottone Spoiler #428
  ✓ Cliccato bottone Spoiler #429
  ✓ Cliccato bottone Spoiler #430
  ✓ Cliccato bottone Spoiler #431
  ✓ Cliccato bottone Spoiler #432
  ✓ Cliccato bottone Spoiler #433
  ✓ Cliccato bottone Spoiler #434
  ✓ Cliccato bottone Spoiler #435
  ✓ Cliccato bottone Spoiler #436
  ✓ Cliccato bottone Spoiler #437
  ✓ Cliccato bottone Spoiler #438
  ✓ Cliccato bottone Spoiler #439
  ✓ Cliccato bottone Spoiler #440
  ✓ Cliccato bottone Spoiler #441
  ✓ Cliccato bottone Spoiler #442
  ✓ Cliccato bottone Spoiler #443
  ✓ Cliccato bottone Spoiler #444
  ✓ Cliccato bottone Spoiler #445
  ✓ Cliccato bottone Spoiler #446
  ✓ Cliccato bottone Spoiler #447
  ✓ Cliccato bottone Spoiler #448
  ✓ Cliccato bottone Spoiler #449
  ✓ Cliccato bottone Spoiler #450
  ✓ Cliccato bottone Spoiler #451
  ✓ Cliccato bottone Spoiler #452
  ✓ Cliccato bottone Spoiler #453
  ✓ Cliccato bottone Spoiler #454
  ✓ Cliccato bottone Spoiler #455
  ✓ Cliccato bottone Spoiler #456
  ✓ Cliccato bottone Spoiler #457
  ✓ Cliccato bottone Spoiler #458
  ✓ Cliccato bottone Spoiler #459
  ✓ Cliccato bottone Spoiler #460
  ✓ Cliccato bottone Spoiler #461
  ✓ Cliccato bottone Spoiler #462
  ✓ Cliccato bottone Spoiler #463
  ✓ Cliccato bottone Spoiler #464
  ✓ Cliccato bottone Spoiler #465
  ✓ Cliccato bottone Spoiler #466
  ✓ Cliccato bottone Spoiler #467
  ✓ Cliccato bottone Spoiler #468
  ✓ Cliccato bottone Spoiler #469
  ✓ Cliccato bottone Spoiler #470
  ✓ Cliccato bottone Spoiler #471
  ✓ Cliccato bottone Spoiler #472
  ✓ Cliccato bottone Spoiler #473
  ✓ Cliccato bottone Spoiler #474
  ✓ Cliccato bottone Spoiler #475
  ✓ Cliccato bottone Spoiler #476
  ✓ Cliccato bottone Spoiler #477
  ✓ Cliccato bottone Spoiler #478
  ✓ Cliccato bottone Spoiler #479
  ✓ Cliccato bottone Spoiler #480
  ✓ Cliccato bottone Spoiler #481
  ✓ Cliccato bottone Spoiler #482
  ✓ Cliccato bottone Spoiler #483
  ✓ Cliccato bottone Spoiler #484
  ✓ Cliccato bottone Spoiler #485
  ✓ Cliccato bottone Spoiler #486
  ✓ Cliccato bottone Spoiler #487
  ✓ Cliccato bottone Spoiler #488
  ✓ Cliccato bottone Spoiler #489
  ✓ Cliccato bottone Spoiler #490
  ✓ Cliccato bottone Spoiler #491
  ✓ Cliccato bottone Spoiler #492
  ✓ Cliccato bottone Spoiler #493
  ✓ Cliccato bottone Spoiler #494
  ✓ Cliccato bottone Spoiler #495
  ✓ Cliccato bottone Spoiler #496
  ✓ Cliccato bottone Spoiler #497
  ✓ Cliccato bottone Spoiler #498
  ✓ Cliccato bottone Spoiler #499
  ✓ Cliccato bottone Spoiler #500
  ✓ Cliccato bottone Spoiler #501
  ✓ Cliccato bottone Spoiler #502
  ✓ Cliccato bottone Spoiler #503
  ✓ Cliccato bottone Spoiler #504
  ✓ Cliccato bottone Spoiler #505
  ✓ Cliccato bottone Spoiler #506
  ✓ Cliccato bottone Spoiler #507
  ✓ Cliccato bottone Spoiler #508
  ✓ Cliccato bottone Spoiler #509
  ✓ Cliccato bottone Spoiler #510
  ✓ Cliccato bottone Spoiler #511
  ✓ Cliccato bottone Spoiler #512
  ✓ Cliccato bottone Spoiler #513
  ✓ Cliccato bottone Spoiler #514
  ✓ Cliccato bottone Spoiler #515
  ✓ Cliccato bottone Spoiler #516
  ✓ Cliccato bottone Spoiler #517
  ✓ Cliccato bottone Spoiler #518
  ✓ Cliccato bottone Spoiler #519
  ✓ Cliccato bottone Spoiler #520
  ✓ Cliccato bottone Spoiler #521
  ✓ Cliccato bottone Spoiler #522
  ✓ Cliccato bottone Spoiler #523
  ✓ Cliccato bottone Spoiler #524
  ✓ Cliccato bottone Spoiler #525
  ✓ Cliccato bottone Spoiler #526
  ✓ Cliccato bottone Spoiler #527
  ✓ Cliccato bottone Spoiler #528
  ✓ Cliccato bottone Spoiler #529
  ✓ Cliccato bottone Spoiler #530
  ✓ Cliccato bottone Spoiler #531
  ✓ Cliccato bottone Spoiler #532
  ✓ Cliccato bottone Spoiler #533
  ✓ Cliccato bottone Spoiler #534
  ✓ Cliccato bottone Spoiler #535
  ✓ Cliccato bottone Spoiler #536
  ✓ Cliccato bottone Spoiler #537
  ✓ Cliccato bottone Spoiler #538
  ✓ Cliccato bottone Spoiler #539
  ✓ Cliccato bottone Spoiler #540
  ✓ Cliccato bottone Spoiler #541
  ✓ Cliccato bottone Spoiler #542
  ✓ Cliccato bottone Spoiler #543
  ✓ Cliccato bottone Spoiler #544
  ✓ Cliccato bottone Spoiler #545
  ✓ Cliccato bottone Spoiler #546
  ✓ Cliccato bottone Spoiler #547
  ✓ Cliccato bottone Spoiler #548
  ✓ Cliccato bottone Spoiler #549
  ✓ Cliccato bottone Spoiler #550
  ✓ Cliccato bottone Spoiler #551
  ✓ Cliccato bottone Spoiler #552
  ✓ Cliccato bottone Spoiler #553
  ✓ Cliccato bottone Spoiler #554
  ✓ Cliccato bottone Spoiler #555
  ✓ Cliccato bottone Spoiler #556
  ✓ Cliccato bottone Spoiler #557
  ✓ Cliccato bottone Spoiler #558
  ✓ Cliccato bottone Spoiler #559
  ✓ Cliccato bottone Spoiler #560
  ✓ Cliccato bottone Spoiler #561
  ✓ Cliccato bottone Spoiler #562
  ✓ Cliccato bottone Spoiler #563
  ✓ Cliccato bottone Spoiler #564
  ✓ Cliccato bottone Spoiler #565
  ✓ Cliccato bottone Spoiler #566
  ✓ Cliccato bottone Spoiler #567
  ✓ Cliccato bottone Spoiler #568
  ✓ Cliccato bottone Spoiler #569
  ✓ Cliccato bottone Spoiler #570
  ✓ Cliccato bottone Spoiler #571
  ✓ Cliccato bottone Spoiler #572
  ✓ Cliccato bottone Spoiler #573
  ✓ Cliccato bottone Spoiler #574
  ✓ Cliccato bottone Spoiler #575
  ✓ Cliccato bottone Spoiler #576
  ✓ Cliccato bottone Spoiler #577
  ✓ Cliccato bottone Spoiler #578
  ✓ Cliccato bottone Spoiler #579
  ✓ Cliccato bottone Spoiler #580
  ✓ Cliccato bottone Spoiler #581
  ✓ Cliccato bottone Spoiler #582
  ✓ Cliccato bottone Spoiler #583
  ✓ Cliccato bottone Spoiler #584
  ✓ Cliccato bottone Spoiler #585
  ✓ Cliccato bottone Spoiler #586
  ✓ Cliccato bottone Spoiler #587
  ✓ Cliccato bottone Spoiler #588
  ✓ Cliccato bottone Spoiler #589

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,1
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,1
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,1
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,1
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,1
...,...,...,...,...,...,...
4371,A little disappointed but it's good!,None,I think most of the bad reviews come from the ...,0,2,7
4372,Hating for the love of the game,None,Consider this as a review for volume 2 as a wh...,0,0,7
4373,Volume two is a whole different show,None,The plot of the show has been lost because the...,0,5,7
4374,not that bad,None,I think the episode was not that bad as everyo...,0,4,7
4375,Stop lying to yourselves,None,Anyone who think this episode is a 10/10 is ju...,0,5,7

In [163]:
# estrazione dati recensioni ottavo episodio quinta stagione. s maggiore perchè numero recensioni molto più ampio
df_temp = data_frame_review_data(url[7], 8, s=540) # estrazione dati recensioni ottavo episodio

df = pd.concat([df, df_temp], ignore_index=True) # uniamo i dati al dataset

df

Cerca bottoni Spoiler...
Trovati 2080 bottoni Spoiler
  ✓ Cliccato bottone Spoiler #1
  ✓ Cliccato bottone Spoiler #2
  ✓ Cliccato bottone Spoiler #3
  ✓ Cliccato bottone Spoiler #4
  ✓ Cliccato bottone Spoiler #5
  ✓ Cliccato bottone Spoiler #6
  ✓ Cliccato bottone Spoiler #7
  ✓ Cliccato bottone Spoiler #8
  ✓ Cliccato bottone Spoiler #9
  ✓ Cliccato bottone Spoiler #10
  ✓ Cliccato bottone Spoiler #11
  ✓ Cliccato bottone Spoiler #12
  ✓ Cliccato bottone Spoiler #13
  ✓ Cliccato bottone Spoiler #14
  ✓ Cliccato bottone Spoiler #15
  ✓ Cliccato bottone Spoiler #16
  ✓ Cliccato bottone Spoiler #17
  ✓ Cliccato bottone Spoiler #18
  ✓ Cliccato bottone Spoiler #19
  ✓ Cliccato bottone Spoiler #20
  ✓ Cliccato bottone Spoiler #21
  ✓ Cliccato bottone Spoiler #22
  ✓ Cliccato bottone Spoiler #23
  ✓ Cliccato bottone Spoiler #24
  ✓ Cliccato bottone Spoiler #25
  ✓ Cliccato bottone Spoiler #26
  ✓ Cliccato bottone Spoiler #27
  ✓ Cliccato bottone Spoiler #28
  ✓ Cliccato bottone Spoiler #29
  ✓ Cliccato bottone Spoiler #30
  ✓ Cliccato bottone Spoiler #31
  ✓ Cliccato bottone Spoiler #32
  ✓ Cliccato bottone Spoiler #33
  ✓ Cliccato bottone Spoiler #34
  ✓ Cliccato bottone Spoiler #35
  ✓ Cliccato bottone Spoiler #36
  ✓ Cliccato bottone Spoiler #37
  ✓ Cliccato bottone Spoiler #38
  ✓ Cliccato bottone Spoiler #39
  ✓ Cliccato bottone Spoiler #40
  ✓ Cliccato bottone Spoiler #41
  ✓ Cliccato bottone Spoiler #42
  ✓ Cliccato bottone Spoiler #43
  ✓ Cliccato bottone Spoiler #44
  ✓ Cliccato bottone Spoiler #45
  ✓ Cliccato bottone Spoiler #46
  ✓ Cliccato bottone Spoiler #47
  ✓ Cliccato bottone Spoiler #48
  ✓ Cliccato bottone Spoiler #49
  ✓ Cliccato bottone Spoiler #50
  ✓ Cliccato bottone Spoiler #51
  ✓ Cliccato bottone Spoiler #52
  ✓ Cliccato bottone Spoiler #53
  ✓ Cliccato bottone Spoiler #54
  ✓ Cliccato bottone Spoiler #55
  ✓ Cliccato bottone Spoiler #56
  ✓ Cliccato bottone Spoiler #57
  ✓ Cliccato bottone Spoiler #58
  ✓ Cliccato bottone Spoiler #59
  ✓ Cliccato bottone Spoiler #60
  ✓ Cliccato bottone Spoiler #61
  ✓ Cliccato bottone Spoiler #62
  ✓ Cliccato bottone Spoiler #63
  ✓ Cliccato bottone Spoiler #64
  ✓ Cliccato bottone Spoiler #65
  ✓ Cliccato bottone Spoiler #66
  ✓ Cliccato bottone Spoiler #67
  ✓ Cliccato bottone Spoiler #68
  ✓ Cliccato bottone Spoiler #69
  ✓ Cliccato bottone Spoiler #70
  ✓ Cliccato bottone Spoiler #71
  ✓ Cliccato bottone Spoiler #72
  ✓ Cliccato bottone Spoiler #73
  ✓ Cliccato bottone Spoiler #74
  ✓ Cliccato bottone Spoiler #75
  ✓ Cliccato bottone Spoiler #76
  ✓ Cliccato bottone Spoiler #77
  ✓ Cliccato bottone Spoiler #78
  ✓ Cliccato bottone Spoiler #79
  ✓ Cliccato bottone Spoiler #80
  ✓ Cliccato bottone Spoiler #81
  ✓ Cliccato bottone Spoiler #82
  ✓ Cliccato bottone Spoiler #83
  ✓ Cliccato bottone Spoiler #84
  ✓ Cliccato bottone Spoiler #85
  ✓ Cliccato bottone Spoiler #86
  ✓ Cliccato bottone Spoiler #87
  ✓ Cliccato bottone Spoiler #88
  ✓ Cliccato bottone Spoiler #89
  ✓ Cliccato bottone Spoiler #90
  ✓ Cliccato bottone Spoiler #91
  ✓ Cliccato bottone Spoiler #92
  ✓ Cliccato bottone Spoiler #93
  ✓ Cliccato bottone Spoiler #94
  ✓ Cliccato bottone Spoiler #95
  ✓ Cliccato bottone Spoiler #96
  ✓ Cliccato bottone Spoiler #97
  ✓ Cliccato bottone Spoiler #98
  ✓ Cliccato bottone Spoiler #99
  ✓ Cliccato bottone Spoiler #100
  ✓ Cliccato bottone Spoiler #101
  ✓ Cliccato bottone Spoiler #102
  ✓ Cliccato bottone Spoiler #103
  ✓ Cliccato bottone Spoiler #104
  ✓ Cliccato bottone Spoiler #105
  ✓ Cliccato bottone Spoiler #106
  ✓ Cliccato bottone Spoiler #107
  ✓ Cliccato bottone Spoiler #108
  ✓ Cliccato bottone Spoiler #109
  ✓ Cliccato bottone Spoiler #110
  ✓ Cliccato bottone Spoiler #111
  ✓ Cliccato bottone Spoiler #112
  ✓ Cliccato bottone Spoiler #113
  ✓ Cliccato bottone Spoiler #114
  ✓ Cliccato bottone Spoiler #115
  ✓ Cliccato bottone Spoiler #116
  ✓ Cliccato bottone Spoiler #117
  ✓ Cliccato bottone Spoiler #118
  ✓ Cliccato bottone Spoiler #119
  ✓ Cliccato bottone Spoiler #120
  ✓ Cliccato bottone Spoiler #121
  ✓ Cliccato bottone Spoiler #122
  ✓ Cliccato bottone Spoiler #123
  ✓ Cliccato bottone Spoiler #124
  ✓ Cliccato bottone Spoiler #125
  ✓ Cliccato bottone Spoiler #126
  ✓ Cliccato bottone Spoiler #127
  ✓ Cliccato bottone Spoiler #128
  ✓ Cliccato bottone Spoiler #129
  ✓ Cliccato bottone Spoiler #130
  ✓ Cliccato bottone Spoiler #131
  ✓ Cliccato bottone Spoiler #132
  ✓ Cliccato bottone Spoiler #133
  ✓ Cliccato bottone Spoiler #134
  ✓ Cliccato bottone Spoiler #135
  ✓ Cliccato bottone Spoiler #136
  ✓ Cliccato bottone Spoiler #137
  ✓ Cliccato bottone Spoiler #138
  ✓ Cliccato bottone Spoiler #139
  ✓ Cliccato bottone Spoiler #140
  ✓ Cliccato bottone Spoiler #141
  ✓ Cliccato bottone Spoiler #142
  ✓ Cliccato bottone Spoiler #143
  ✓ Cliccato bottone Spoiler #144
  ✓ Cliccato bottone Spoiler #145
  ✓ Cliccato bottone Spoiler #146
  ✓ Cliccato bottone Spoiler #147
  ✓ Cliccato bottone Spoiler #148
  ✓ Cliccato bottone Spoiler #149
  ✓ Cliccato bottone Spoiler #150
  ✓ Cliccato bottone Spoiler #151
  ✓ Cliccato bottone Spoiler #152
  ✓ Cliccato bottone Spoiler #153
  ✓ Cliccato bottone Spoiler #154
  ✓ Cliccato bottone Spoiler #155
  ✓ Cliccato bottone Spoiler #156
  ✓ Cliccato bottone Spoiler #157
  ✓ Cliccato bottone Spoiler #158
  ✓ Cliccato bottone Spoiler #159
  ✓ Cliccato bottone Spoiler #160
  ✓ Cliccato bottone Spoiler #161
  ✓ Cliccato bottone Spoiler #162
  ✓ Cliccato bottone Spoiler #163
  ✓ Cliccato bottone Spoiler #164
  ✓ Cliccato bottone Spoiler #165
  ✓ Cliccato bottone Spoiler #166
  ✓ Cliccato bottone Spoiler #167
  ✓ Cliccato bottone Spoiler #168
  ✓ Cliccato bottone Spoiler #169
  ✓ Cliccato bottone Spoiler #170
  ✓ Cliccato bottone Spoiler #171
  ✓ Cliccato bottone Spoiler #172
  ✓ Cliccato bottone Spoiler #173
  ✓ Cliccato bottone Spoiler #174
  ✓ Cliccato bottone Spoiler #175
  ✓ Cliccato bottone Spoiler #176
  ✓ Cliccato bottone Spoiler #177
  ✓ Cliccato bottone Spoiler #178
  ✓ Cliccato bottone Spoiler #179
  ✓ Cliccato bottone Spoiler #180
  ✓ Cliccato bottone Spoiler #181
  ✓ Cliccato bottone Spoiler #182
  ✓ Cliccato bottone Spoiler #183
  ✓ Cliccato bottone Spoiler #184
  ✓ Cliccato bottone Spoiler #185
  ✓ Cliccato bottone Spoiler #186
  ✓ Cliccato bottone Spoiler #187
  ✓ Cliccato bottone Spoiler #188
  ✓ Cliccato bottone Spoiler #189
  ✓ Cliccato bottone Spoiler #190
  ✓ Cliccato bottone Spoiler #191
  ✓ Cliccato bottone Spoiler #192
  ✓ Cliccato bottone Spoiler #193
  ✓ Cliccato bottone Spoiler #194
  ✓ Cliccato bottone Spoiler #195
  ✓ Cliccato bottone Spoiler #196
  ✓ Cliccato bottone Spoiler #197
  ✓ Cliccato bottone Spoiler #198
  ✓ Cliccato bottone Spoiler #199
  ✓ Cliccato bottone Spoiler #200
  ✓ Cliccato bottone Spoiler #201
  ✓ Cliccato bottone Spoiler #202
  ✓ Cliccato bottone Spoiler #203
  ✓ Cliccato bottone Spoiler #204
  ✓ Cliccato bottone Spoiler #205
  ✓ Cliccato bottone Spoiler #206
  ✓ Cliccato bottone Spoiler #207
  ✓ Cliccato bottone Spoiler #208
  ✓ Cliccato bottone Spoiler #209
  ✓ Cliccato bottone Spoiler #210
  ✓ Cliccato bottone Spoiler #211
  ✓ Cliccato bottone Spoiler #212
  ✓ Cliccato bottone Spoiler #213
  ✓ Cliccato bottone Spoiler #214
  ✓ Cliccato bottone Spoiler #215
  ✓ Cliccato bottone Spoiler #216
  ✓ Cliccato bottone Spoiler #217
  ✓ Cliccato bottone Spoiler #218
  ✓ Cliccato bottone Spoiler #219
  ✓ Cliccato bottone Spoiler #220
  ✓ Cliccato bottone Spoiler #221
  ✓ Cliccato bottone Spoiler #222
  ✓ Cliccato bottone Spoiler #223
  ✓ Cliccato bottone Spoiler #224
  ✓ Cliccato bottone Spoiler #225
  ✓ Cliccato bottone Spoiler #226
  ✓ Cliccato bottone Spoiler #227
  ✓ Cliccato bottone Spoiler #228
  ✓ Cliccato bottone Spoiler #229
  ✓ Cliccato bottone Spoiler #230
  ✓ Cliccato bottone Spoiler #231
  ✓ Cliccato bottone Spoiler #232
  ✓ Cliccato bottone Spoiler #233
  ✓ Cliccato bottone Spoiler #234
  ✓ Cliccato bottone Spoiler #235
  ✓ Cliccato bottone Spoiler #236
  ✓ Cliccato bottone Spoiler #237
  ✓ Cliccato bottone Spoiler #238
  ✓ Cliccato bottone Spoiler #239
  ✓ Cliccato bottone Spoiler #240
  ✓ Cliccato bottone Spoiler #241
  ✓ Cliccato bottone Spoiler #242
  ✓ Cliccato bottone Spoiler #243
  ✓ Cliccato bottone Spoiler #244
  ✓ Cliccato bottone Spoiler #245
  ✓ Cliccato bottone Spoiler #246
  ✓ Cliccato bottone Spoiler #247
  ✓ Cliccato bottone Spoiler #248
  ✓ Cliccato bottone Spoiler #249
  ✓ Cliccato bottone Spoiler #250
  ✓ Cliccato bottone Spoiler #251
  ✓ Cliccato bottone Spoiler #252
  ✓ Cliccato bottone Spoiler #253
  ✓ Cliccato bottone Spoiler #254
  ✓ Cliccato bottone Spoiler #255
  ✓ Cliccato bottone Spoiler #256
  ✓ Cliccato bottone Spoiler #257
  ✓ Cliccato bottone Spoiler #258
  ✓ Cliccato bottone Spoiler #259
  ✓ Cliccato bottone Spoiler #260
  ✓ Cliccato bottone Spoiler #261
  ✓ Cliccato bottone Spoiler #262
  ✓ Cliccato bottone Spoiler #263
  ✓ Cliccato bottone Spoiler #264
  ✓ Cliccato bottone Spoiler #265
  ✓ Cliccato bottone Spoiler #266
  ✓ Cliccato bottone Spoiler #267
  ✓ Cliccato bottone Spoiler #268
  ✓ Cliccato bottone Spoiler #269
  ✓ Cliccato bottone Spoiler #270
  ✓ Cliccato bottone Spoiler #271
  ✓ Cliccato bottone Spoiler #272
  ✓ Cliccato bottone Spoiler #273
  ✓ Cliccato bottone Spoiler #274
  ✓ Cliccato bottone Spoiler #275
  ✓ Cliccato bottone Spoiler #276
  ✓ Cliccato bottone Spoiler #277
  ✓ Cliccato bottone Spoiler #278
  ✓ Cliccato bottone Spoiler #279
  ✓ Cliccato bottone Spoiler #280
  ✓ Cliccato bottone Spoiler #281
  ✓ Cliccato bottone Spoiler #282
  ✓ Cliccato bottone Spoiler #283
  ✓ Cliccato bottone Spoiler #284
  ✓ Cliccato bottone Spoiler #285
  ✓ Cliccato bottone Spoiler #286
  ✓ Cliccato bottone Spoiler #287
  ✓ Cliccato bottone Spoiler #288
  ✓ Cliccato bottone Spoiler #289
  ✓ Cliccato bottone Spoiler #290
  ✓ Cliccato bottone Spoiler #291
  ✓ Cliccato bottone Spoiler #292
  ✓ Cliccato bottone Spoiler #293
  ✓ Cliccato bottone Spoiler #294
  ✓ Cliccato bottone Spoiler #295
  ✓ Cliccato bottone Spoiler #296
  ✓ Cliccato bottone Spoiler #297
  ✓ Cliccato bottone Spoiler #298
  ✓ Cliccato bottone Spoiler #299
  ✓ Cliccato bottone Spoiler #300
  ✓ Cliccato bottone Spoiler #301
  ✓ Cliccato bottone Spoiler #302
  ✓ Cliccato bottone Spoiler #303
  ✓ Cliccato bottone Spoiler #304
  ✓ Cliccato bottone Spoiler #305
  ✓ Cliccato bottone Spoiler #306
  ✓ Cliccato bottone Spoiler #307
  ✓ Cliccato bottone Spoiler #308
  ✓ Cliccato bottone Spoiler #309
  ✓ Cliccato bottone Spoiler #310
  ✓ Cliccato bottone Spoiler #311
  ✓ Cliccato bottone Spoiler #312
  ✓ Cliccato bottone Spoiler #313
  ✓ Cliccato bottone Spoiler #314
  ✓ Cliccato bottone Spoiler #315
  ✓ Cliccato bottone Spoiler #316
  ✓ Cliccato bottone Spoiler #317
  ✓ Cliccato bottone Spoiler #318
  ✓ Cliccato bottone Spoiler #319
  ✓ Cliccato bottone Spoiler #320
  ✓ Cliccato bottone Spoiler #321
  ✓ Cliccato bottone Spoiler #322
  ✓ Cliccato bottone Spoiler #323
  ✓ Cliccato bottone Spoiler #324
  ✓ Cliccato bottone Spoiler #325
  ✓ Cliccato bottone Spoiler #326
  ✓ Cliccato bottone Spoiler #327
  ✓ Cliccato bottone Spoiler #328
  ✓ Cliccato bottone Spoiler #329
  ✓ Cliccato bottone Spoiler #330
  ✓ Cliccato bottone Spoiler #331
  ✓ Cliccato bottone Spoiler #332
  ✓ Cliccato bottone Spoiler #333
  ✓ Cliccato bottone Spoiler #334
  ✓ Cliccato bottone Spoiler #335
  ✓ Cliccato bottone Spoiler #336
  ✓ Cliccato bottone Spoiler #337
  ✓ Cliccato bottone Spoiler #338
  ✓ Cliccato bottone Spoiler #339
  ✓ Cliccato bottone Spoiler #340
  ✓ Cliccato bottone Spoiler #341
  ✓ Cliccato bottone Spoiler #342
  ✓ Cliccato bottone Spoiler #343
  ✓ Cliccato bottone Spoiler #344
  ✓ Cliccato bottone Spoiler #345
  ✓ Cliccato bottone Spoiler #346
  ✓ Cliccato bottone Spoiler #347
  ✓ Cliccato bottone Spoiler #348
  ✓ Cliccato bottone Spoiler #349
  ✓ Cliccato bottone Spoiler #350
  ✓ Cliccato bottone Spoiler #351
  ✓ Cliccato bottone Spoiler #352
  ✓ Cliccato bottone Spoiler #353
  ✓ Cliccato bottone Spoiler #354
  ✓ Cliccato bottone Spoiler #355
  ✓ Cliccato bottone Spoiler #356
  ✓ Cliccato bottone Spoiler #357
  ✓ Cliccato bottone Spoiler #358
  ✓ Cliccato bottone Spoiler #359
  ✓ Cliccato bottone Spoiler #360
  ✓ Cliccato bottone Spoiler #361
  ✓ Cliccato bottone Spoiler #362
  ✓ Cliccato bottone Spoiler #363
  ✓ Cliccato bottone Spoiler #364
  ✓ Cliccato bottone Spoiler #365
  ✓ Cliccato bottone Spoiler #366
  ✓ Cliccato bottone Spoiler #367
  ✓ Cliccato bottone Spoiler #368
  ✓ Cliccato bottone Spoiler #369
  ✓ Cliccato bottone Spoiler #370
  ✓ Cliccato bottone Spoiler #371
  ✓ Cliccato bottone Spoiler #372
  ✓ Cliccato bottone Spoiler #373
  ✓ Cliccato bottone Spoiler #374
  ✓ Cliccato bottone Spoiler #375
  ✓ Cliccato bottone Spoiler #376
  ✓ Cliccato bottone Spoiler #377
  ✓ Cliccato bottone Spoiler #378
  ✓ Cliccato bottone Spoiler #379
  ✓ Cliccato bottone Spoiler #380
  ✓ Cliccato bottone Spoiler #381
  ✓ Cliccato bottone Spoiler #382
  ✓ Cliccato bottone Spoiler #383
  ✓ Cliccato bottone Spoiler #384
  ✓ Cliccato bottone Spoiler #385
  ✓ Cliccato bottone Spoiler #386
  ✓ Cliccato bottone Spoiler #387
  ✓ Cliccato bottone Spoiler #388
  ✓ Cliccato bottone Spoiler #389
  ✓ Cliccato bottone Spoiler #390
  ✓ Cliccato bottone Spoiler #391
  ✓ Cliccato bottone Spoiler #392
  ✓ Cliccato bottone Spoiler #393
  ✓ Cliccato bottone Spoiler #394
  ✓ Cliccato bottone Spoiler #395
  ✓ Cliccato bottone Spoiler #396
  ✓ Cliccato bottone Spoiler #397
  ✓ Cliccato bottone Spoiler #398
  ✓ Cliccato bottone Spoiler #399
  ✓ Cliccato bottone Spoiler #400
  ✓ Cliccato bottone Spoiler #401
  ✓ Cliccato bottone Spoiler #402
  ✓ Cliccato bottone Spoiler #403
  ✓ Cliccato bottone Spoiler #404
  ✓ Cliccato bottone Spoiler #405
  ✓ Cliccato bottone Spoiler #406
  ✓ Cliccato bottone Spoiler #407
  ✓ Cliccato bottone Spoiler #408
  ✓ Cliccato bottone Spoiler #409
  ✓ Cliccato bottone Spoiler #410
  ✓ Cliccato bottone Spoiler #411
  ✓ Cliccato bottone Spoiler #412
  ✓ Cliccato bottone Spoiler #413
  ✓ Cliccato bottone Spoiler #414
  ✓ Cliccato bottone Spoiler #415
  ✓ Cliccato bottone Spoiler #416
  ✓ Cliccato bottone Spoiler #417
  ✓ Cliccato bottone Spoiler #418
  ✓ Cliccato bottone Spoiler #419
  ✓ Cliccato bottone Spoiler #420
  ✓ Cliccato bottone Spoiler #421
  ✓ Cliccato bottone Spoiler #422
  ✓ Cliccato bottone Spoiler #423
  ✓ Cliccato bottone Spoiler #424
  ✓ Cliccato bottone Spoiler #425
  ✓ Cliccato bottone Spoiler #426
  ✓ Cliccato bottone Spoiler #427
  ✓ Cliccato bottone Spoiler #428
  ✓ Cliccato bottone Spoiler #429
  ✓ Cliccato bottone Spoiler #430
  ✓ Cliccato bottone Spoiler #431
  ✓ Cliccato bottone Spoiler #432
  ✓ Cliccato bottone Spoiler #433
  ✓ Cliccato bottone Spoiler #434
  ✓ Cliccato bottone Spoiler #435
  ✓ Cliccato bottone Spoiler #436
  ✓ Cliccato bottone Spoiler #437
  ✓ Cliccato bottone Spoiler #438
  ✓ Cliccato bottone Spoiler #439
  ✓ Cliccato bottone Spoiler #440
  ✓ Cliccato bottone Spoiler #441
  ✓ Cliccato bottone Spoiler #442
  ✓ Cliccato bottone Spoiler #443
  ✓ Cliccato bottone Spoiler #444
  ✓ Cliccato bottone Spoiler #445
  ✓ Cliccato bottone Spoiler #446
  ✓ Cliccato bottone Spoiler #447
  ✓ Cliccato bottone Spoiler #448
  ✓ Cliccato bottone Spoiler #449
  ✓ Cliccato bottone Spoiler #450
  ✓ Cliccato bottone Spoiler #451
  ✓ Cliccato bottone Spoiler #452
  ✓ Cliccato bottone Spoiler #453
  ✓ Cliccato bottone Spoiler #454
  ✓ Cliccato bottone Spoiler #455
  ✓ Cliccato bottone Spoiler #456
  ✓ Cliccato bottone Spoiler #457
  ✓ Cliccato bottone Spoiler #458
  ✓ Cliccato bottone Spoiler #459
  ✓ Cliccato bottone Spoiler #460
  ✓ Cliccato bottone Spoiler #461
  ✓ Cliccato bottone Spoiler #462
  ✓ Cliccato bottone Spoiler #463
  ✓ Cliccato bottone Spoiler #464
  ✓ Cliccato bottone Spoiler #465
  ✓ Cliccato bottone Spoiler #466
  ✓ Cliccato bottone Spoiler #467
  ✓ Cliccato bottone Spoiler #468
  ✓ Cliccato bottone Spoiler #469
  ✓ Cliccato bottone Spoiler #470
  ✓ Cliccato bottone Spoiler #471
  ✓ Cliccato bottone Spoiler #472
  ✓ Cliccato bottone Spoiler #473
  ✓ Cliccato bottone Spoiler #474
  ✓ Cliccato bottone Spoiler #475
  ✓ Cliccato bottone Spoiler #476
  ✓ Cliccato bottone Spoiler #477
  ✓ Cliccato bottone Spoiler #478
  ✓ Cliccato bottone Spoiler #479
  ✓ Cliccato bottone Spoiler #480
  ✓ Cliccato bottone Spoiler #481
  ✓ Cliccato bottone Spoiler #482
  ✓ Cliccato bottone Spoiler #483
  ✓ Cliccato bottone Spoiler #484
  ✓ Cliccato bottone Spoiler #485
  ✓ Cliccato bottone Spoiler #486
  ✓ Cliccato bottone Spoiler #487
  ✓ Cliccato bottone Spoiler #488
  ✓ Cliccato bottone Spoiler #489
  ✓ Cliccato bottone Spoiler #490
  ✓ Cliccato bottone Spoiler #491
  ✓ Cliccato bottone Spoiler #492
  ✓ Cliccato bottone Spoiler #493
  ✓ Cliccato bottone Spoiler #494
  ✓ Cliccato bottone Spoiler #495
  ✓ Cliccato bottone Spoiler #496
  ✓ Cliccato bottone Spoiler #497
  ✓ Cliccato bottone Spoiler #498
  ✓ Cliccato bottone Spoiler #499
  ✓ Cliccato bottone Spoiler #500
  ✓ Cliccato bottone Spoiler #501
  ✓ Cliccato bottone Spoiler #502
  ✓ Cliccato bottone Spoiler #503
  ✓ Cliccato bottone Spoiler #504
  ✓ Cliccato bottone Spoiler #505
  ✓ Cliccato bottone Spoiler #506
  ✓ Cliccato bottone Spoiler #507
  ✓ Cliccato bottone Spoiler #508
  ✓ Cliccato bottone Spoiler #509
  ✓ Cliccato bottone Spoiler #510
  ✓ Cliccato bottone Spoiler #511
  ✓ Cliccato bottone Spoiler #512
  ✓ Cliccato bottone Spoiler #513
  ✓ Cliccato bottone Spoiler #514
  ✓ Cliccato bottone Spoiler #515
  ✓ Cliccato bottone Spoiler #516
  ✓ Cliccato bottone Spoiler #517
  ✓ Cliccato bottone Spoiler #518
  ✓ Cliccato bottone Spoiler #519
  ✓ Cliccato bottone Spoiler #520
  ✓ Cliccato bottone Spoiler #521
  ✓ Cliccato bottone Spoiler #522
  ✓ Cliccato bottone Spoiler #523
  ✓ Cliccato bottone Spoiler #524
  ✓ Cliccato bottone Spoiler #525
  ✓ Cliccato bottone Spoiler #526
  ✓ Cliccato bottone Spoiler #527
  ✓ Cliccato bottone Spoiler #528
  ✓ Cliccato bottone Spoiler #529
  ✓ Cliccato bottone Spoiler #530
  ✓ Cliccato bottone Spoiler #531
  ✓ Cliccato bottone Spoiler #532
  ✓ Cliccato bottone Spoiler #533
  ✓ Cliccato bottone Spoiler #534
  ✓ Cliccato bottone Spoiler #535
  ✓ Cliccato bottone Spoiler #536
  ✓ Cliccato bottone Spoiler #537
  ✓ Cliccato bottone Spoiler #538
  ✓ Cliccato bottone Spoiler #539
  ✓ Cliccato bottone Spoiler #540
  ✓ Cliccato bottone Spoiler #541
  ✓ Cliccato bottone Spoiler #542
  ✓ Cliccato bottone Spoiler #543
  ✓ Cliccato bottone Spoiler #544
  ✓ Cliccato bottone Spoiler #545
  ✓ Cliccato bottone Spoiler #546
  ✓ Cliccato bottone Spoiler #547
  ✓ Cliccato bottone Spoiler #548
  ✓ Cliccato bottone Spoiler #549
  ✓ Cliccato bottone Spoiler #550
  ✓ Cliccato bottone Spoiler #551
  ✓ Cliccato bottone Spoiler #552
  ✓ Cliccato bottone Spoiler #553
  ✓ Cliccato bottone Spoiler #554
  ✓ Cliccato bottone Spoiler #555
  ✓ Cliccato bottone Spoiler #556
  ✓ Cliccato bottone Spoiler #557
  ✓ Cliccato bottone Spoiler #558
  ✓ Cliccato bottone Spoiler #559
  ✓ Cliccato bottone Spoiler #560
  ✓ Cliccato bottone Spoiler #561
  ✓ Cliccato bottone Spoiler #562
  ✓ Cliccato bottone Spoiler #563
  ✓ Cliccato bottone Spoiler #564
  ✓ Cliccato bottone Spoiler #565
  ✓ Cliccato bottone Spoiler #566
  ✓ Cliccato bottone Spoiler #567
  ✓ Cliccato bottone Spoiler #568
  ✓ Cliccato bottone Spoiler #569
  ✓ Cliccato bottone Spoiler #570
  ✓ Cliccato bottone Spoiler #571
  ✓ Cliccato bottone Spoiler #572
  ✓ Cliccato bottone Spoiler #573
  ✓ Cliccato bottone Spoiler #574
  ✓ Cliccato bottone Spoiler #575
  ✓ Cliccato bottone Spoiler #576
  ✓ Cliccato bottone Spoiler #577
  ✓ Cliccato bottone Spoiler #578
  ✓ Cliccato bottone Spoiler #579
  ✓ Cliccato bottone Spoiler #580
  ✓ Cliccato bottone Spoiler #581
  ✓ Cliccato bottone Spoiler #582
  ✓ Cliccato bottone Spoiler #583
  ✓ Cliccato bottone Spoiler #584
  ✓ Cliccato bottone Spoiler #585
  ✓ Cliccato bottone Spoiler #586
  ✓ Cliccato bottone Spoiler #587
  ✓ Cliccato bottone Spoiler #588
  ✓ Cliccato bottone Spoiler #589

,titolo,rating,recensione,upvote,downvote,episodio
0,Shaky start for me but I love how everything u...,8,"At first, I felt a little disoriented watching...",23,3,1
1,Poor Dustin,8,"Season 5 opens with a confident, character-dri...",26,5,1
2,Chapter One: The Crawl,8,A good start to the final season. Despite the ...,33,8,1
3,The Beginning of the End,8,This first episode was a great opening for the...,44,13,1
4,A good start,9,"To summarize my opinion on this episode, its a...",54,27,1
...,...,...,...,...,...,...
7932,DISAPOINTMENTTTT,1,I'm honestly really angry about the Stranger T...,0,1,8
7933,bittersweet nostalgic ending still can't cover...,None,Stranger things was my childhood and I grew up...,0,0,8
7934,So many loose ends...,None,"For casual viewers, they don't neccessarily se...",0,0,8
7935,Understand the ending,None,I think why so many people are disappointed wi...,0,0,8
7936,Plot armor strikes once again 🤦🏻,None,First of all. It was a good episode. Loved the...,0,2,8

In [166]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

In [167]:
df.to_excel("stranger_things.xlsx")